src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import *

app_name = "api"
routes = routers.DefaultRouter()
routes.register("customers", UserViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Tatoo API",
        default_version="v1",
        description="Chose and get tatoo what you like",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path("", include(routes.urls)),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("pinner/<int:pk>/", PinnerAPIView.as_view(), name="pinner_detail"),
    path("pinner/update/<int:pk>/", PinnerUpdateAPIView.as_view(), name="pinner_update"),
    path("pinner/delete/<int:pk>/", PinnerDestroyAPIView.as_view(), name="pinner_delete"),
    path("boards/", BoardListAPIView.as_view(), name="boards_list"),
    path("board/<int:pk>/", BoardDetailAPIView.as_view(), name="board_detail"),
    path("board/update/<int:pk>/", BoardUpdateAPIView.as_view(), name="board_update"),
    path("board/delete/<int:pk>/", BoardDestroyAPIView.as_view(), name="board_delete"),
    path("pins/", PinListAPIView.as_view(), name="pins_list"),
    path("pins/<int:pk>/", PinDetailAPIView.as_view(), name="pin_detail"),
    path("pins/update/<int:pk>/", PinUpdateAPIView.as_view(), name="pin_update"),
    path("pins/delete/<int:pk>/", PinDestroyAPIView.as_view(), name="pin_delete"),
    path("images/", ImageListAPIView.as_view(), name="images_list"),
    path("image/<int:pk>/", ImageDetailAPIView.as_view(), name="image_detail"),
    path("image/update/<int:pk>/", ImageUpdateAPIView.as_view(), name="image_update"),
    path("image/delete/<int:pk>/", ImageDestroyAPIView.as_view(), name="image_delete"),
    path("comments/", CommentListAPIView.as_view(), name="comments_list"),
    path("comment/<int:pk>/", CommentDetailAPIView.as_view(), name="comment_detail"),
    path("comment/update/<int:pk>/", CommentUpdateAPIView.as_view(), name="comment_update"),
    path("comment/delete/<int:pk>/", CommentDestroyAPIView.as_view(), name="comment_delete"),
]

src/tatoo/urls.py
from django.urls import path

from tatoo.views import Explore, IndexView, Pin_detail, RegisterView, UserLoginView, UserLogoutView, UserProfileView, \
    UserEditProfileView, CreateBoardView

app_name = "tatoo"

urlpatterns = [
    path("", IndexView.as_view(), name="index_page"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/<int:pk>", UserEditProfileView.as_view(), name="edit_profile"),
    path("explore/", Explore.as_view(), name="explore"),
    path("pin/<int:pk>", Pin_detail.as_view(), name="pin_detail"),
    path("board/create/", CreateBoardView.as_view(), name="create_board")
]

src/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'tattoo/assets/favicon.png' %}"/>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tattoo/css/main.css' %}">
    <title>Artcore - Tattoo freedom</title>
</head>
<body>
<header class="p-3 bg-white sticky-top">
    <div class="">
        <div class="d-flex flex-wrap align-items-center justify-content-center">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                     class="gUZ lZJ U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true" aria-label=""
                     role="img">
                    <path d="M0 12c0 5.123 3.211 9.497 7.73 11.218-.11-.937-.227-2.482.025-3.566.217-.932 1.401-5.938 1.401-5.938s-.357-.715-.357-1.774c0-1.66.962-2.9 2.161-2.9 1.02 0 1.512.765 1.512 1.682 0 1.025-.653 2.557-.99 3.978-.281 1.189.597 2.159 1.769 2.159 2.123 0 3.756-2.239 3.756-5.471 0-2.861-2.056-4.86-4.991-4.86-3.398 0-5.393 2.549-5.393 5.184 0 1.027.395 2.127.889 2.726a.36.36 0 0 1 .083.343c-.091.378-.293 1.189-.332 1.355-.053.218-.173.265-.4.159-1.492-.694-2.424-2.875-2.424-4.627 0-3.769 2.737-7.229 7.892-7.229 4.144 0 7.365 2.953 7.365 6.899 0 4.117-2.595 7.431-6.199 7.431-1.211 0-2.348-.63-2.738-1.373 0 0-.599 2.282-.744 2.84-.282 1.084-1.064 2.456-1.549 3.235C9.584 23.815 10.77 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12"
                          fill="#E60023" stroke-width="0px"></path>
                </svg>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% block header %}
                <li><a style='border-radius: 50px; font-size: 15px;' href="{% url 'tatoo:index_page' %}"
                       class="ms-3 nav-link px-2 text-white bg-black"><b>Home</b></a></li>
                <li><a href="{% url 'tatoo:explore' %}" class="ms-1 nav-link px-2 link-dark"><b>Explore</b></a></li>
                {% endblock %}
            </ul>
            <form action="" class="col-12 w-75 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input name="q" style="background-color: #e1e1e1;" type="search"
                       class="pt-2 pb-2 form-control border rounded-pill" placeholder="Search" aria-label="Search">
            </form>
            <div class="ms-">
                <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                     class="me-3 gUZ B9u U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true"
                     aria-label="" role="img">
                    <path d="M12 24c-1.66 0-3-1.34-3-3h6c0 1.66-1.34 3-3 3zm7-10.83c1.58 1.52 2.67 3.55 3 5.83H2c.33-2.28 1.42-4.31 3-5.83V7c0-3.87 3.13-7 7-7s7 3.13 7 7v6.17z"
                          fill="#767676" stroke-width="0px"></path>
                </svg>
                <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                     class="me-3 Hn_ gUZ B9u U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true"
                     aria-label="" role="img">
                    <path d="M18 12.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 18 12.5m-6 0a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 12.5m-6 0a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 6 12.5M12 0C5.925 0 1 4.925 1 11c0 2.653.94 5.086 2.504 6.986L2 24l5.336-3.049A10.93 10.93 0 0 0 12 22c6.075 0 11-4.925 11-11S18.075 0 12 0"
                          fill="#767676" stroke-width="0px"></path>
                </svg>
            </div>
            <a href="{% url 'tatoo:profile' %}">
                <img src="{% static 'tattoo/images/default_icon.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <div class="dropdown text-end">
                <a href="#" class="ms-3 d-block link-dark text-decoration-none" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                         class="gUZ B9u U9O kVc" height="12" width="12" viewBox="0 0 24 24" aria-hidden="true"
                         aria-label="" role="img">
                        <path d="M12 19.5.66 8.29c-.88-.86-.88-2.27 0-3.14.88-.87 2.3-.87 3.18 0L12 13.21l8.16-8.06c.88-.87 2.3-.87 3.18 0 .88.87.88 2.28 0 3.14L12 19.5z"
                              fill="#767676" stroke-width="0px"></path>
                    </svg>
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="">{{ user.email }}</a></li>
                        <li><a class="dropdown-item" href="">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'tatoo:logout' %}">Sign out</a></li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'tatoo:login' %}">Sign in</a></li>
                        <li><a class="dropdown-item" href="{% url 'tatoo:register' %}">Registration</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</header>
    {% block content %}

    <div class="main-page">
        <div class="main-page__hero">
            <h1 class="main-page__title">Artcore</h1>
            <h2 class="main-page__subtitle">FIND THE RIGHT ARTIST FOR YOUR NEXT TATTOO</h2>
            <p class="main-page__description">
                Because getting a tattoo should be a great experience. We work with only the best tattoo studios, and
                we’ll connect you to the right artist for your idea.
            </p>
        </div>
    </div>

    {% endblock %}
<!-- Bootstrap JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="{% static 'tattoo/js/main.js' %}"></script>
</body>
</html>

src/templates/base/explore.html
{% extends "base/base.html" %}

{% block header %}
    <li><a href="{% url 'tatoo:index_page' %}" class="ms-1 nav-link px-2 link-dark"><b>Home</b></a></li>
    <li><a style='border-radius: 50px; font-size: 15px;' href="{% url 'tatoo:explore' %}" class="ms-1 nav-link px-2 text-white bg-black"><b>Explore</b></a></li>
{% endblock %}

{% block content %}
<main class="ms-3 me-3">
    <div id="masonry">
    {% for pin in pins %}
        <a class="m-2" href="{% url 'tatoo:pin_detail' pin.id %}">
            <img class="shadow p-3 mb-5 bg-white rounded" height="350"  src="{{ pin.img.image.url }}">
        </a>
    {% endfor %}
    </div>
</main>


{% endblock %}