src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import *

app_name = "api"
routes = routers.DefaultRouter()
routes.register("customers", UserViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Tatoo API",
        default_version="v1",
        description="Chose and get tatoo what you like",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path("", include(routes.urls)),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("pinner/<int:pk>/", PinnerAPIView.as_view(), name="pinner_detail"),
    path("pinner/update/<int:pk>/", PinnerUpdateAPIView.as_view(), name="pinner_update"),
    path("pinner/delete/<int:pk>/", PinnerDestroyAPIView.as_view(), name="pinner_delete"),
    path("boards/", BoardListAPIView.as_view(), name="boards_list"),
    path("board/<int:pk>/", BoardDetailAPIView.as_view(), name="board_detail"),
    path("board/update/<int:pk>/", BoardUpdateAPIView.as_view(), name="board_update"),
    path("board/delete/<int:pk>/", BoardDestroyAPIView.as_view(), name="board_delete"),
    path("pins/", PinListAPIView.as_view(), name="pins_list"),
    path("pins/<int:pk>/", PinDetailAPIView.as_view(), name="pin_detail"),
    path("pins/update/<int:pk>/", PinUpdateAPIView.as_view(), name="pin_update"),
    path("pins/delete/<int:pk>/", PinDestroyAPIView.as_view(), name="pin_delete"),
    path("images/", ImageListAPIView.as_view(), name="images_list"),
    path("image/<int:pk>/", ImageDetailAPIView.as_view(), name="image_detail"),
    path("image/update/<int:pk>/", ImageUpdateAPIView.as_view(), name="image_update"),
    path("image/delete/<int:pk>/", ImageDestroyAPIView.as_view(), name="image_delete"),
    path("comments/", CommentListAPIView.as_view(), name="comments_list"),
    path("comment/<int:pk>/", CommentDetailAPIView.as_view(), name="comment_detail"),
    path("comment/update/<int:pk>/", CommentUpdateAPIView.as_view(), name="comment_update"),
    path("comment/delete/<int:pk>/", CommentDestroyAPIView.as_view(), name="comment_delete"),
]

src/tatoo/urls.py
from django.urls import path

from tatoo.views import Explore, IndexView, Pin_detail, RegisterView, UserLoginView, UserLogoutView, UserProfileView, \
    UserEditProfileView, CreateBoardView

app_name = "tatoo"

urlpatterns = [
    path("", IndexView.as_view(), name="index_page"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/<int:pk>", UserEditProfileView.as_view(), name="edit_profile"),
    path("explore/", Explore.as_view(), name="explore"),
    path("pin/<int:pk>", Pin_detail.as_view(), name="pin_detail"),
    path("board/create/", CreateBoardView.as_view(), name="create_board")
]

src/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField

from accounts.managers import CustomerManager


class Customer(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    is_tattoo_master = models.BooleanField(default=False, blank=True)
    phone = PhoneNumberField(
        _("Phone number"), null=True, blank=True,)

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )

    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )

    objects = CustomerManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

src/templates/accounts/edit_profile.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row profile-page">
        <div class="col-md-8 ps-5 pe-5 pt-3 pb-5 ">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h2 class="text-black"><b>Public Profile</b></h2>
                <p class="mb-4" >People visiting your profile will see the following info</p>
                <div class="row mt-1">
                    {{ form|crispy }}
                    <div class="col-md-8 mt-3">
                        <button type="submit" class="red-btn btn ps-4 pe-4 pt-3 pb-3 text-white"><b>Save</b></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

src/templates/accounts/first_header.html
<div class="p-3 bg-white first-header">
    <div class="d-flex flex-wrap align-items-center justify-content-center">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pinterest_Logo.svg/1200px-Pinterest_Logo.svg.png" width="120" height="33" alt="">
        </a>
        <ul class="nav ms-5 col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"></ul>
        <div class="dropdown text-end">
            <a class="text-decoration-none text-black me-4" href="#"><b>About</b></a>
            <a class="text-decoration-none text-black me-4" href="#"><b>Business</b></a>
            <a class="text-decoration-none text-black me-5" href="#"><b>Blog</b></a>
            <a href="" id="loginBtn" class="red-btn btn text-white "><b>Login</b></a>
            <a href="{% url 'tatoo:index_page' %}" class="main-btn btn text-black ms-3"><b>Sign Up</b></a>
        </div>
    </div>
</div>

src/templates/accounts/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tattoo/css/main.css' %}">
    <title>Artcore</title>
</head>
{% include 'accounts/first_header.html' %}
<body class="login-bg" style="height: 100vh;">
    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Login</b></h3>
        <div class="row">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary" value="Login" >Login</button>
            </form>
            <small class="text-muted mt-3">
                New Here? <a class="text-decoration-none" href="{% url 'tatoo:register' %}">Create account</a>
            </small>
        </div>
    </div>
</body>
</html>

src/templates/accounts/profile.html
{% extends "base/base.html" %}
{% block content %}
<main class="profile-page">
    <div class="col-md-10 text-center">
    {% if request.user == user %}
    <!-- plus icon | create board and pins dropdown menu -->
    <div class="dropdown">
        <a style="float: right; margin-top: 430px;" href="#"class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path d="M22 10h-8V2a2 2 0 0 0-4 0v8H2a2 2 0 0 0 0 4h8v8a2 2 0 0 0 4 0v-8h8a2 2 0 0 0 0-4" fill="#111111" stroke-width="0px"></path>
            </svg>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
            <li><a id="createBoardBtn" class="dropdown-item" href="#">Create Board</a></li>
            <li><a class="dropdown-item" href="">Create Pin</a></li>
        </ul>
    </div>
    {% endif %}
    <!-- user public information -->
    <!-- user photo -->
    {% if user.profile.avatar %}
        <img style="object-fit: cover;" width="150" height="150" class="rounded-circle" src="{{ user.profile.avatar.url }}" alt="">
    {% else %}
        <img style="object-fit: cover;" width="150" height="150" class="rounded-circle" src="../../tatoo/static/tattoo/images/default_icon.png" alt="">
    {% endif %}
    <!-- Username or first and last name -->
    <h1 class="text-black"><b>{% if user.profile.first_name %}{{ user.profile.first_name }} {{ user.profile.last_name }}{% else %}{{ user.profile.username }}{% endif %}</b></h1>
    <!-- username and pronouns -->
    <p class="text-muted">{{ user.email }} - {% if user.is_tattoo_master %} Tattoo Master ✔ {% else %} Customer {% endif %}</p>
    <!-- birthdate and about -->
    <p><b><a class="text-black text-decoration-none" href=""></a></b>{{ user.profile.birthdate }}</p>
    <p><b><a class="text-black text-decoration-none" href=""></a></b>{{ user.profile.about }}</p>
    <!-- following and followers count -->
    <span><b>followers : </b></span>
    <span><b>following : </b></span>
    {% if request.user == user %}
    <!-- edit profile and share btn -->
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-1"><b>Share</b></a>
        <a href="{% url 'tatoo:edit_profile' user.pk %}" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-1"><b>Edit Profile</b></a>
    </div>
    {% elif is_following %}
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-4"><b>Message</b></a>
        <a href="{% url 'accounts:unfollow' user.username %}" class="following-btn btn ps-3 pt-2 pb-2 pe-3 text-white ms-1 me-4"><b>Following</b></a>
        <a href="#">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#111111" stroke-width="0px"></path>
            </svg>
        </a>
    </div>
    {% else %}
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-4"><b>Message</b></a>
        <a href="{% url 'accounts:follow' user.username %}" class="red-btn btn ps-3 pt-2 pb-2 pe-3 text-white ms-1 me-4">
            <b>Follow</b>
        </a>
        <a href="#">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path
                    d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z"
                    fill="#111111"
                    stroke-width="0px">
                </path>
            </svg>
        </a>
    </div>
    {% endif %}
    <!-- saved and created tab -->
    <div class="mt-5 mb-5">
        <a href="" class="btn-select-border text-decoration-none ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Created</b>
        </a>
        <a href="" class="btn ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Saved</b>
        </a>
    </div>
    <!-- create board modal -->
    <div id="simpleModal" class="modal">
        <div class="modal-content ps-5 pb-5 pe-5">
            <h3 class="mt-4 mb-3"><b>Create Board</b></h3>
            <div class="row">
                <form method="post" action="{% url 'tatoo:create_board' %}">
                    {% csrf_token %}
                    <label>
                        Name {{ create_board_form.name }}
                    </label>
                    <label>
                        {{ create_board_form.pins_count }}
                        <input value="0" name="pins_count">
                    </label>
                    <label>
                        {{ create_board_form.pinner }}
                        <input value="{{ user.pk }}" name="userId">
                    </label>

                    <div style="text-align:left" class="col-md-11">
                        <b class="ms-1">Keep this board secret</b>
                        <p class="text-muted ms-4">So only you and collaborators can see it. Learm more</p>
                    </div>
                    <input class="modal-red-btn btn text-white mt-3" type="submit" value="Create">
                </form>
            </div>
        </div>
    </div>
    {% if '_saved' in request.get_full_path %}
    <!-- user boards -->
    <div id="boards" class="row">
        {% for board in boards %}
            {% if request.user != user %}
                <!-- do not show private boards to people -->
                {% if not board.is_private %}
                    <div class="col-md-2 ms-2 me-4 mb-2">
                        <a href="{% url 'boards:board_detail' username=board.user.username board_name=board.title %}">
                            <img style="object-fit: cover; border-radius: 20px;" height="200" width="200" src="{{ board.cover.url }}">
                            <h4 class="mt-2 text-black" style="float: left;"><b>{{ board.title }}</b></h4>
                        </a>
                    </div>
                {% endif %}
                {% elif request.user == user %}
                    <div class="col-md-2 ms-2 me-4 mb-2">
                        <a href="{% url 'boards:board_detail' username=board.user.username board_name=board.title %}">
                            <img style="object-fit: cover; border-radius: 20px;" height="200" width="200" src="{{ board.cover.url }}">
                            <h4 class="mt-2 text-black" style="float: left;  overflow: hidden;"><b>{{ board.title }}</b></h4>
                        </a>
                        <a style="float: right;" href="{% url 'boards:edit_board' board.id %}">
                            <div class="mb-2"></div>
                            <svg class="main-btn p-1 rounded-circle" class="gUZ pBj U9O kVc" height="25" width="25" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                                <path d="m13.386 6.018 4.596 4.596L7.097 21.499 1 22.999l1.501-6.096L13.386 6.018zm8.662-4.066a3.248 3.248 0 0 1 0 4.596l-2.298 2.3-4.596-4.598 2.298-2.299a3.248 3.248 0 0 1 4.596 0z"></path>
                            </svg>
                        </a>
                    </div>
                {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <!-- user created pins -->
    <div class="row">
        {% for pin in created_pins %}
        <div class="img-container col-md-2 ms-2 me-4 mb-3">
            <a href="{% url 'pins:pin_detail' pin.id %}">
                {% if pin.get_type == 'video' %}
                    <video autoplay muted loop class="video" >
                        <source src="{{ pin.file.url }}" >
                    </video>
                {% elif pin.get_type == 'image' %}
                    <img style="object-fit: cover; border-radius: 20px; cursor: zoom-in;" height="300" width="200" src="{{ pin.file.url }}">
                {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
</main>
{% endblock %}

src/templates/accounts/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tattoo/css/main.css' %}">
    <title>Artcore</title>
</head>
{% include 'accounts/first_header.html' %}
<body class="login-bg" style="height: 100vh;">
    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Create account</b></h3>
        <div class="row">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary" value="Register" >Register</button>
            </form>
            <small class="text-muted mt-3">
                Already have an account? <a class="text-decoration-none" href="">Login Here</a>
            </small>
        </div>
    </div>
</body>

</html>